// Generated by https://quicktype.io

export interface Cliente {
    id?:             number;
    identificacion: string;
    nombre:         string;
    direccion:      string;
    telefono:       string;
    correo:         string;
    created_at?:     string;
    updated_at?:     string;
}
